export const REQUEST_DATA = 'REQUEST_DATA';
export const REQUEST_DATA_SUCCESS = 'REQUEST_DATA_SUCCESS';
export const REQUEST_DATA_FAILURE = 'REQUEST_DATA_FAILURE';
export const UPDATE_QUERY = 'UPDATE_QUERY';
